### ISSUE TITLE
PDF encryption feature

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#106]
Apache FOP supports encryption of PDF: https://xmlgraphics.apache.org/fop/2.6/pdfencryption.html

Add PDF's encryption support to mn2pdf.

Tasks:
- [x] how to pass parameters for pdf encryption into mn2pdf
- [x] check how java encryption api is working in non-Oracle JVM (`The PDF encryption implemented in FOP does not need external libraries to perform encryption. A recent JDK (1.5+) is sufficient. However, encryption using keys with 256 bits requires the installation of the JCE Unlimited Strength Jurisdiction Policy files from Oracle`)
- [x] update mn2pdf

**Comment by Intelligent2013** [comment]
How to pass parameters into mn2pdf:
1. via command line. Additional parameters for mn2pdf are:
<html><body>


parameter | description
-- | --
-encryption-length | encryption length in bit
-ownerPassword | owner password
-userPassword | user password
-noprint | disable printing
-nocopy | disable copy/paste of content
-noedit | disable editing in Adobe Acrobat
-noannotations | disable editing of annotations
-nofillinforms | disable filling in forms
-noaccesscontent | disable text and graphics extraction for accessibility purposes
-noassembledoc | disable assembling documents
-noprinthq | disable high quality printing


</body>
</html>

2. via external .yml file (parameter `--encryption-parameters <filename>`, like fontist's manifest file:
```yaml
encryption-length: 128
ownerPassword: mypass
userPassword: userpass
print: false
copy: true
edit: false
annotations: true
fillinforms: false
accesscontent: true
assembledoc: false
printhq: true
```

@ronaldtse what is best way to pass the parameters?

**Comment by ronaldtse** [comment]
@Intelligent2013 for passing parameters we can do both? From the Ruby side it is easy to pass a YAML file.

**Comment by ronaldtse** [comment]
@Intelligent2013 for mn2pdf, we should use a consistent camelCase or hyphenation set of strings.

Probably these?

```
userPassword: String, may be null

ownerPassword: String, may be null

allowPrint: true if printing is allowed

allowCopyContent: true if copying content is allowed

allowEditContent: true if editing content is allowed

allowEditAnnotations: true if editing annotations is allowed

allowFillInForms: true if filling in forms is allowed.

allowAccessContent: true if extracting text and graphics is allowed

allowAssembleDocument: true if assembling document is allowed

allowPrintHq: true if printing to high quality is allowed

encryptMetadata: true if the Metadata stream should be encrypted
```

**Comment by Intelligent2013** [comment]
> for passing parameters we can do both? From the Ruby side it is easy to pass a YAML file.

@ronaldtse yes, sure. Will do both.

> for mn2pdf, we should use a consistent camelCase or hyphenation set of strings.

@ronaldtse mn2pdf uses 'hyphenation' already (`--xml-file`, `--xsl-file`, ...). So, command line parameters are:
<html><body>


parameter | description
-- | --
--encryption-length | encryption length in bit
--owner-password | owner password
--user-password | user password
--allow-print <true(default)\|false> | 'false' for disable printing
--allow-copy-content <true(default)\|false> | 'false' for disable copy/paste of content
--allow-edit-content <true(default)\|false> | 'false' for disable editing in Adobe Acrobat
--allow-edit-annotations <true(default)\|false> | 'false' for disable editing of annotations
--allow-fill-in-forms <true(default)\|false> | 'false' for disable filling in forms
--allow-access-content <true(default)\|false> | 'false' for disable text and graphics extraction for accessibility purposes
--allow-assemble-document <true(default)\|false> | 'false' for disable assembling documents
--allow-print-hq <true(default)\|false> | 'false' for disable high quality printing
--encrypt-metadata <true(default)\|false> |'false' for disable encrypt the Metadata stream


</body>
</html>

YAML file example:
```yaml
encryption-length: 128
owner-password: mypass
user-password: userpass
allow-print: false
allow-copy-content: true
allow-edit-content: false
allow-edit-annotations: true
allow-fill-in-forms: false
allow-access-content: true
allow-assemble-document: false
allow-print-hq: true
encrypt-metadata: true
```
