### ISSUE TITLE
Wrong Inter 'variable font' rendering

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#235]
Source: https://github.com/metanorma/metanorma-iso/issues/1079

Fontist manifest:
```
Inter:
  Regular:
    full_name: Inter Regular
    paths:
    - C:/Users/TestUser/.fontist/fonts/Inter-Regular.ttf
    - C:/Users/TestUser/.fontist/fonts/Inter-VariableFont_slnt,wght.ttf
  Bold:
    full_name: Inter Bold
    paths:
    - C:/Users/TestUser/.fontist/fonts/Inter-Bold.ttf
```

The issue occurs due the font `Inter-VariableFont_slnt,wght.ttf`:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/1ead4135-a0c6-4524-a4ad-ae211cd82d8b)

Rendering with `Inter-Regular.ttf`:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/61bdf1c2-e9f4-4bbe-9949-8c981073e941)
