### ISSUE TITLE
Take a new command line option of a "font manifest" which provides paths

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#52]
In executing mn2pdf, we may have fonts installed in other places outside of the designated directory or the system paths. Fontist is a new gem that allows us to install custom fonts and detect fonts.

The format described in https://github.com/fontist/fontist#install can be used to "pass" font path information to mn2pdf, e.g. in YAML

```yaml
Segoe UI:
  Regular:
    - "/Users/user/.fontist/fonts/SEGOEUI.TTF",
  Bold:
    - "/Users/user/.fontist/fonts/SEGOEUIB.TTF"
Roboto Mono:
  Regular:
```

This task is to allow mn2pdf to take a file path argument that accepts a font path manifest.

This is necessary for Metanorma to use the correct fonts.

**Comment by Intelligent2013** [comment]
@ronaldtse  it is possible to get the font's paths from fontist manifest. But please note that fontist yaml file isn't a replacement for FOP config file. In any case, initially, font should be determined in FOP config file, because it allows to set additional (mandatory in some cases) properties like these:
- sub-font (for .ttc font, <font kerning="yes" embed-url="cambria.ttc" sub-font="Cambria Math">...)
- simulate-style, to create programmatically italic and bold glyphs

**Comment by ronaldtse** [comment]
@Intelligent2013 the purpose of the fontist manifest is to provide font paths for mn2pdf. Fontist supports sub-fonts (TTF within a TTC, and extracting TTF from TTC).

It is not meant as a replacement for fop config. It is however meant as a communication mechanism between Metanorma Ruby and mn2pdf — because Metanorma Ruby is responsible for installing all the fonts needed by mn2pdf. 

Could you list out what parameters you need so that Metanorma Ruby can install all fonts needed for mn2pdf? And @alexeymorozov can make that available in Fontist for you.

**Comment by Intelligent2013** [comment]
> Could you list out what parameters you need so that Metanorma Ruby can install all fonts needed for mn2pdf? And @alexeymorozov can make that available in Fontist for you

@ronaldtse I need one thing - in case of font is TTC, then I need:
- specify sub-font name in yaml file, for example (one file cambria.ttc with different font names):
```yaml
Cambria:
  Regular:
    - "/Users/user/.fontist/fonts/cambria.ttc",
Cambria Math:
  Regular:
    - "/Users/user/.fontist/fonts/cambria.ttc",
```
as font filename ends on '.ttc' I will know that I have to specify sub-font in FOP config

or

- extract TTFs from TTC into a standalone files, and yaml will look like this:
```yaml
Cambria:
  Regular:
    - "/Users/user/.fontist/fonts/cambria.ttf",
Cambria Math:
  Regular:
    - "/Users/user/.fontist/fonts/cambria_math.ttf",
```

**Comment by ronaldtse** [comment]
@Intelligent2013 I believe this is already how it works. @alexeymorozov could we support this sort of manifest output in Fontist?

**Comment by ronaldtse** [comment]
I'm re-running the last job.

**Comment by alexeymorozov** [comment]
@Intelligent2013 @ronaldtse Yes, the first style of output is already supported. This is what is returned from fontist now:

```yaml
$ cat manifest.yml
---
Cambria:
- Regular
Cambria Math:
- Regular
```

```yaml
$ fontist manifest-locations manifest.yml
---
Cambria:
  Regular:
  - "/Users/user/.fontist/fonts/CAMBRIA.TTC"
Cambria Math:
  Regular:
  - "/Users/user/.fontist/fonts/CAMBRIA.TTC"
```

**Comment by Intelligent2013** [comment]
@alexeymorozov great, thank you!

**Comment by Intelligent2013** [comment]
@alexeymorozov 
I'm trying to understand the fontist output format and have a question.

`fontist status "Cambria"` displays correct info about Cambria font:
```
 Cambria
  Regular (C:/Users/IntlUser/.fontist/fonts/cambria.ttc)
 Cambria Math
  Regular (C:/Users/IntlUser/.fontist/fonts/cambria.ttc)
```

I've installed fonts 'Source Han Sans' by the command:
`fontist install "Source Han Sans"`, 
and the command `fontist status "Source Han Sans"` displays:

(example for SourceHanSans-Normal.ttc)
```
...
 Source Han Sans
  Normal (C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc)
 Source Han Sans HC
  Normal (C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc)
 Source Han Sans K
  Normal (C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc)
 Source Han Sans SC
  Normal (C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc)
 Source Han Sans TC
  Normal (C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc)
...
```

But in font file `SourceHanSans-Normal.`**ttc** there aren't sub-fonts `Source Han Sans`, ` Source Han Sans HC`, ...
ttc contains these fonts:
![изображение](https://user-images.githubusercontent.com/5559926/99886413-61cf1f80-2c4d-11eb-96dd-20dcdea717a6.png)
(FontForge screenshot)

I.e. font name from fontist + ' Normal'.

Is it a bug? Or I did something wrong?

**Comment by alexeymorozov** [comment]
It's intentional, full name of font could be obtained by Font + Style (Source Han Sans + Normal).

Does it cause some problems?

**Comment by Intelligent2013** [comment]
> 
> 
> It's intentional, full name of font could be obtained by Font + Style (Source Han Sans + Normal).
> 
> Does it cause some problems?

To produce the PDF with Apache FOP I have to specify which font to select for TrueType collection (.ttc fonts).
If I'll use the rule `Font + Style`, then for
`Source Han Sans + Normal` => `Source Han Sans Normal` it's working ok,
but for
`Cambria Math + Regular` => `Cambria Math Regular`, or
`Cambria + Regular` => `Cambria Regular`,  but in cambria.ttc there isn't fonts `Cambria Math Regular` and `Cambria Regular`:
![изображение](https://user-images.githubusercontent.com/5559926/99906196-cab6a600-2ce6-11eb-9385-02ea7e8a894a.png)

**Comment by ronaldtse** [comment]
> full name of font could be obtained by Font + Style (Source Han Sans + Normal).

Looks like the "font style" name of font is separate from the "font name inside a collection". Perhaps we have to provide the "font style" to "font name inside a collection" mapping inside Fontist / YAML?

**Comment by Intelligent2013** [comment]
Looks like there is an issue in the manifest file. I think that the field `fonts/styles/full_name` should be used instead of `fonts/name`. As said in the section **Declaring font collections and their fonts** https://github.com/fontist/formulas/#declaring-font-collections-and-their-fonts:

* `fonts`: this works slightly different than from the `fonts` at the top level. It still takes two attributes, the font family name and a styles hash. The styles hash only accepts `type` and `full_name`, which is a map from the font style (e.g., "`Bold`") to the font name **inside** the font collection.

In the yml `Formulas\cleartype.yml ` there isn't full_name for 'Cambria Math':
```
font_collections:
- filename: CAMBRIA.TTC
  fonts:
  - name: Cambria
    styles:
    - type: Regular
      full_name: Cambria
  - name: Cambria Math
    styles:
    - type: Regular
```
therefore I propose if font from `font_collections`, then  get the field `fonts/styles/full_name` if exist only, and `fonts/name` for another cases.

**Comment by alexeymorozov** [comment]
The full name attribute can be added. Will this be ok?

```yaml
$ fontist manifest-locations manifest.yml
---
Cambria:
  Regular:
    full_name: "Cambria"
    path: "/Users/user/.fontist/fonts/CAMBRIA.TTC"
Cambria Math:
  Regular:
    full_name: "Cambria Math"
    path: "/Users/user/.fontist/fonts/CAMBRIA.TTC"
```

Also let's discuss a request format. Is it convenient to build a manifest it this format?

```yaml
$ cat manifest.yml
---
Cambria:
- Regular
Cambria Math:
- Regular
```

Or it's easier to request by full name too?

```yaml
$ cat manifest.yml
---
- Cambria
- Cambria Math
- Source Han Sans Normal

$ fontist manifest-locations manifest.yml
---
Cambria: "C:/Users/MyUser/.fontist/fonts/CAMBRIA.TTC"
Cambria Math: "C:/Users/MyUser/.fontist/fonts/CAMBRIA.TTC"
Source Han Sans Normal: "C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc"
```

**Comment by Intelligent2013** [comment]
> The full name attribute can be added. Will this be ok?
> 
> ```yaml
> $ fontist manifest-locations manifest.yml
> ---
> Cambria:
>   Regular:
>     full_name: "Cambria"
>     path: "/Users/user/.fontist/fonts/CAMBRIA.TTC"
> Cambria Math:
>   Regular:
>     full_name: "Cambria Math"
>     path: "/Users/user/.fontist/fonts/CAMBRIA.TTC"
> ```
>

Ok, I agree.

> Also let's discuss a request format. Is it convenient to build a manifest with this format?
> 
> ```yaml
> $ cat manifest.yml
> ---
> Cambria:
> - Regular
> Cambria Math:
> - Regular
> ```
> 
> Or it's easier to request by full name too?
> 
> ```yaml
> $ cat manifest.yml
> ---
> - Cambria
> - Cambria Math
> - Source Han Sans Normal
> 
> $ fontist manifest-locations manifest.yml
> ---
> Cambria: "C:/Users/MyUser/.fontist/fonts/CAMBRIA.TTC"
> Cambria Math: "C:/Users/MyUser/.fontist/fonts/CAMBRIA.TTC"
> Source Han Sans Normal: "C:/Users/MyUser/.fontist/fonts/SourceHanSans-Normal.ttc"
> ```

No need to change this format, this is not convenient and further processing will be complicated. In this case we mix font name and style and one entity for usual .ttf font. All is need is additional field 'sub-font' name for ttc font ('full_name' field).

**Comment by alexeymorozov** [comment]
Ok, I'll do the first solution: provide 'full_name' field.

**Comment by ronaldtse** [comment]
Sounds good, thanks!

**Comment by Intelligent2013** [comment]
Option ` --font-manifest` added in the release https://github.com/metanorma/mn2pdf/releases/tag/v1.23.
Expected format for font manifest file in the version 1.23 is:
```yaml
Cambria:
  Regular:
  - "~/.fontist/fonts/CAMBRIA.TTC"
  Bold:
  - "~/.fontist/fonts/CAMBRIAB.TTF"
  Italic:
  - "~/.fontist/fonts/CAMBRIAI.TTF"
  Bold Italic:
  - "~/.fontist/fonts/CAMBRIAZ.TTF"
Cambria Math:
  Regular:
  - "~/.fontist/fonts/CAMBRIA.TTC"
```

Support for `full_name` field will be added in next version.
