### ISSUE TITLE
mn2pdf doesn't substitute font path for Source Han Sans Normal

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#63]
For https://github.com/metanorma/mn-samples-iso/pull/72.

From fontist manifest file:
```
  Normal:
    full_name: Source Han Sans Normal
    paths:
    - C:/Users/User1/.fontist/fonts/SourceHanSans-Normal.ttc
 ```

From pdf_fonts_config.xml.out file:
```
<font embed-url="file:/C:/Users/User1/.metanorma/fonts/SourceHanSans-Normal.ttc" kerning="yes" mn_default="true" simulate-style="true" sub-font="Source Han Sans Normal">
	<font-triplet name="Source Han Sans" style="italic" weight="normal"/>
</font>
```
