### ISSUE TITLE
Add font support with dash in name

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#97]
As titled.
Example:
```yaml
BSI Gesta:
  Regular:
    full_name: BSIGesta
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta.otf
  Bold:
    full_name: BSIGesta-Bold
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta-Bold.otf
  Italic:
    full_name: BSIGesta-Italic
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta-Italic.otf
  Bold Italic:
    full_name: BSIGesta-BoldItalic
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta-BoldItalic.otf
  Light:
    full_name: BSIGesta-Light
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta-Light.otf
  Medium:
    full_name: BSIGesta-Medium
    paths:
    - C:/Users/TestUser/.fontist/fonts/BSIGesta-Medium.otf

```

Example without dash:
```yaml
Lato:
  Bold:
    full_name: Lato Bold
    paths:
    - C:/Users/TestUser/.fontist/fonts/Lato-Bold.ttf
  Bold Italic:
    full_name: Lato Bold Italic
    paths:
    - C:/Users/TestUser/.fontist/fonts/Lato-BoldItalic.ttf
```
